# Generated by Django 3.0.5 on 2024-03-13 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
