# Generated by Django 3.0.5 on 2024-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_course_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_duration',
            field=models.PositiveIntegerField(),
        ),
    ]
