# Generated by Django 3.0.5 on 2024-03-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20240317_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
