# Generated by Django 3.0.5 on 2024-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_course_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
