# Generated by Django 3.0.5 on 2024-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_course_exam_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
