# Generated by Django 3.0.5 on 2024-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_courseselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
